// Code generated by MockGen. DO NOT EDIT.
// Source: client/grpc/grpc_generated_v2/grpc_service_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=client/grpc/grpc_generated_v2/grpc_service_grpc.pb.go -destination=mocks/mock_grpc_service_grpc.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	grpc_generated_v2 "github.com/Trendyol/go-triton-client/client/grpc/grpc_generated_v2"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockGRPCInferenceServiceClient is a mock of GRPCInferenceServiceClient interface.
type MockGRPCInferenceServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockGRPCInferenceServiceClientMockRecorder
	isgomock struct{}
}

// MockGRPCInferenceServiceClientMockRecorder is the mock recorder for MockGRPCInferenceServiceClient.
type MockGRPCInferenceServiceClientMockRecorder struct {
	mock *MockGRPCInferenceServiceClient
}

// NewMockGRPCInferenceServiceClient creates a new mock instance.
func NewMockGRPCInferenceServiceClient(ctrl *gomock.Controller) *MockGRPCInferenceServiceClient {
	mock := &MockGRPCInferenceServiceClient{ctrl: ctrl}
	mock.recorder = &MockGRPCInferenceServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGRPCInferenceServiceClient) EXPECT() *MockGRPCInferenceServiceClientMockRecorder {
	return m.recorder
}

// CudaSharedMemoryRegister mocks base method.
func (m *MockGRPCInferenceServiceClient) CudaSharedMemoryRegister(ctx context.Context, in *grpc_generated_v2.CudaSharedMemoryRegisterRequest, opts ...grpc.CallOption) (*grpc_generated_v2.CudaSharedMemoryRegisterResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CudaSharedMemoryRegister", varargs...)
	ret0, _ := ret[0].(*grpc_generated_v2.CudaSharedMemoryRegisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CudaSharedMemoryRegister indicates an expected call of CudaSharedMemoryRegister.
func (mr *MockGRPCInferenceServiceClientMockRecorder) CudaSharedMemoryRegister(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CudaSharedMemoryRegister", reflect.TypeOf((*MockGRPCInferenceServiceClient)(nil).CudaSharedMemoryRegister), varargs...)
}

// CudaSharedMemoryStatus mocks base method.
func (m *MockGRPCInferenceServiceClient) CudaSharedMemoryStatus(ctx context.Context, in *grpc_generated_v2.CudaSharedMemoryStatusRequest, opts ...grpc.CallOption) (*grpc_generated_v2.CudaSharedMemoryStatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CudaSharedMemoryStatus", varargs...)
	ret0, _ := ret[0].(*grpc_generated_v2.CudaSharedMemoryStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CudaSharedMemoryStatus indicates an expected call of CudaSharedMemoryStatus.
func (mr *MockGRPCInferenceServiceClientMockRecorder) CudaSharedMemoryStatus(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CudaSharedMemoryStatus", reflect.TypeOf((*MockGRPCInferenceServiceClient)(nil).CudaSharedMemoryStatus), varargs...)
}

// CudaSharedMemoryUnregister mocks base method.
func (m *MockGRPCInferenceServiceClient) CudaSharedMemoryUnregister(ctx context.Context, in *grpc_generated_v2.CudaSharedMemoryUnregisterRequest, opts ...grpc.CallOption) (*grpc_generated_v2.CudaSharedMemoryUnregisterResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CudaSharedMemoryUnregister", varargs...)
	ret0, _ := ret[0].(*grpc_generated_v2.CudaSharedMemoryUnregisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CudaSharedMemoryUnregister indicates an expected call of CudaSharedMemoryUnregister.
func (mr *MockGRPCInferenceServiceClientMockRecorder) CudaSharedMemoryUnregister(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CudaSharedMemoryUnregister", reflect.TypeOf((*MockGRPCInferenceServiceClient)(nil).CudaSharedMemoryUnregister), varargs...)
}

// LogSettings mocks base method.
func (m *MockGRPCInferenceServiceClient) LogSettings(ctx context.Context, in *grpc_generated_v2.LogSettingsRequest, opts ...grpc.CallOption) (*grpc_generated_v2.LogSettingsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LogSettings", varargs...)
	ret0, _ := ret[0].(*grpc_generated_v2.LogSettingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LogSettings indicates an expected call of LogSettings.
func (mr *MockGRPCInferenceServiceClientMockRecorder) LogSettings(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogSettings", reflect.TypeOf((*MockGRPCInferenceServiceClient)(nil).LogSettings), varargs...)
}

// ModelConfig mocks base method.
func (m *MockGRPCInferenceServiceClient) ModelConfig(ctx context.Context, in *grpc_generated_v2.ModelConfigRequest, opts ...grpc.CallOption) (*grpc_generated_v2.ModelConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ModelConfig", varargs...)
	ret0, _ := ret[0].(*grpc_generated_v2.ModelConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModelConfig indicates an expected call of ModelConfig.
func (mr *MockGRPCInferenceServiceClientMockRecorder) ModelConfig(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelConfig", reflect.TypeOf((*MockGRPCInferenceServiceClient)(nil).ModelConfig), varargs...)
}

// ModelInfer mocks base method.
func (m *MockGRPCInferenceServiceClient) ModelInfer(ctx context.Context, in *grpc_generated_v2.ModelInferRequest, opts ...grpc.CallOption) (*grpc_generated_v2.ModelInferResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ModelInfer", varargs...)
	ret0, _ := ret[0].(*grpc_generated_v2.ModelInferResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModelInfer indicates an expected call of ModelInfer.
func (mr *MockGRPCInferenceServiceClientMockRecorder) ModelInfer(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelInfer", reflect.TypeOf((*MockGRPCInferenceServiceClient)(nil).ModelInfer), varargs...)
}

// ModelMetadata mocks base method.
func (m *MockGRPCInferenceServiceClient) ModelMetadata(ctx context.Context, in *grpc_generated_v2.ModelMetadataRequest, opts ...grpc.CallOption) (*grpc_generated_v2.ModelMetadataResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ModelMetadata", varargs...)
	ret0, _ := ret[0].(*grpc_generated_v2.ModelMetadataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModelMetadata indicates an expected call of ModelMetadata.
func (mr *MockGRPCInferenceServiceClientMockRecorder) ModelMetadata(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelMetadata", reflect.TypeOf((*MockGRPCInferenceServiceClient)(nil).ModelMetadata), varargs...)
}

// ModelReady mocks base method.
func (m *MockGRPCInferenceServiceClient) ModelReady(ctx context.Context, in *grpc_generated_v2.ModelReadyRequest, opts ...grpc.CallOption) (*grpc_generated_v2.ModelReadyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ModelReady", varargs...)
	ret0, _ := ret[0].(*grpc_generated_v2.ModelReadyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModelReady indicates an expected call of ModelReady.
func (mr *MockGRPCInferenceServiceClientMockRecorder) ModelReady(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelReady", reflect.TypeOf((*MockGRPCInferenceServiceClient)(nil).ModelReady), varargs...)
}

// ModelStatistics mocks base method.
func (m *MockGRPCInferenceServiceClient) ModelStatistics(ctx context.Context, in *grpc_generated_v2.ModelStatisticsRequest, opts ...grpc.CallOption) (*grpc_generated_v2.ModelStatisticsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ModelStatistics", varargs...)
	ret0, _ := ret[0].(*grpc_generated_v2.ModelStatisticsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModelStatistics indicates an expected call of ModelStatistics.
func (mr *MockGRPCInferenceServiceClientMockRecorder) ModelStatistics(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelStatistics", reflect.TypeOf((*MockGRPCInferenceServiceClient)(nil).ModelStatistics), varargs...)
}

// ModelStreamInfer mocks base method.
func (m *MockGRPCInferenceServiceClient) ModelStreamInfer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[grpc_generated_v2.ModelInferRequest, grpc_generated_v2.ModelStreamInferResponse], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ModelStreamInfer", varargs...)
	ret0, _ := ret[0].(grpc.BidiStreamingClient[grpc_generated_v2.ModelInferRequest, grpc_generated_v2.ModelStreamInferResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModelStreamInfer indicates an expected call of ModelStreamInfer.
func (mr *MockGRPCInferenceServiceClientMockRecorder) ModelStreamInfer(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelStreamInfer", reflect.TypeOf((*MockGRPCInferenceServiceClient)(nil).ModelStreamInfer), varargs...)
}

// RepositoryIndex mocks base method.
func (m *MockGRPCInferenceServiceClient) RepositoryIndex(ctx context.Context, in *grpc_generated_v2.RepositoryIndexRequest, opts ...grpc.CallOption) (*grpc_generated_v2.RepositoryIndexResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RepositoryIndex", varargs...)
	ret0, _ := ret[0].(*grpc_generated_v2.RepositoryIndexResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RepositoryIndex indicates an expected call of RepositoryIndex.
func (mr *MockGRPCInferenceServiceClientMockRecorder) RepositoryIndex(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepositoryIndex", reflect.TypeOf((*MockGRPCInferenceServiceClient)(nil).RepositoryIndex), varargs...)
}

// RepositoryModelLoad mocks base method.
func (m *MockGRPCInferenceServiceClient) RepositoryModelLoad(ctx context.Context, in *grpc_generated_v2.RepositoryModelLoadRequest, opts ...grpc.CallOption) (*grpc_generated_v2.RepositoryModelLoadResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RepositoryModelLoad", varargs...)
	ret0, _ := ret[0].(*grpc_generated_v2.RepositoryModelLoadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RepositoryModelLoad indicates an expected call of RepositoryModelLoad.
func (mr *MockGRPCInferenceServiceClientMockRecorder) RepositoryModelLoad(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepositoryModelLoad", reflect.TypeOf((*MockGRPCInferenceServiceClient)(nil).RepositoryModelLoad), varargs...)
}

// RepositoryModelUnload mocks base method.
func (m *MockGRPCInferenceServiceClient) RepositoryModelUnload(ctx context.Context, in *grpc_generated_v2.RepositoryModelUnloadRequest, opts ...grpc.CallOption) (*grpc_generated_v2.RepositoryModelUnloadResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RepositoryModelUnload", varargs...)
	ret0, _ := ret[0].(*grpc_generated_v2.RepositoryModelUnloadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RepositoryModelUnload indicates an expected call of RepositoryModelUnload.
func (mr *MockGRPCInferenceServiceClientMockRecorder) RepositoryModelUnload(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepositoryModelUnload", reflect.TypeOf((*MockGRPCInferenceServiceClient)(nil).RepositoryModelUnload), varargs...)
}

// ServerLive mocks base method.
func (m *MockGRPCInferenceServiceClient) ServerLive(ctx context.Context, in *grpc_generated_v2.ServerLiveRequest, opts ...grpc.CallOption) (*grpc_generated_v2.ServerLiveResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ServerLive", varargs...)
	ret0, _ := ret[0].(*grpc_generated_v2.ServerLiveResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ServerLive indicates an expected call of ServerLive.
func (mr *MockGRPCInferenceServiceClientMockRecorder) ServerLive(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServerLive", reflect.TypeOf((*MockGRPCInferenceServiceClient)(nil).ServerLive), varargs...)
}

// ServerMetadata mocks base method.
func (m *MockGRPCInferenceServiceClient) ServerMetadata(ctx context.Context, in *grpc_generated_v2.ServerMetadataRequest, opts ...grpc.CallOption) (*grpc_generated_v2.ServerMetadataResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ServerMetadata", varargs...)
	ret0, _ := ret[0].(*grpc_generated_v2.ServerMetadataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ServerMetadata indicates an expected call of ServerMetadata.
func (mr *MockGRPCInferenceServiceClientMockRecorder) ServerMetadata(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServerMetadata", reflect.TypeOf((*MockGRPCInferenceServiceClient)(nil).ServerMetadata), varargs...)
}

// ServerReady mocks base method.
func (m *MockGRPCInferenceServiceClient) ServerReady(ctx context.Context, in *grpc_generated_v2.ServerReadyRequest, opts ...grpc.CallOption) (*grpc_generated_v2.ServerReadyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ServerReady", varargs...)
	ret0, _ := ret[0].(*grpc_generated_v2.ServerReadyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ServerReady indicates an expected call of ServerReady.
func (mr *MockGRPCInferenceServiceClientMockRecorder) ServerReady(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServerReady", reflect.TypeOf((*MockGRPCInferenceServiceClient)(nil).ServerReady), varargs...)
}

// SystemSharedMemoryRegister mocks base method.
func (m *MockGRPCInferenceServiceClient) SystemSharedMemoryRegister(ctx context.Context, in *grpc_generated_v2.SystemSharedMemoryRegisterRequest, opts ...grpc.CallOption) (*grpc_generated_v2.SystemSharedMemoryRegisterResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SystemSharedMemoryRegister", varargs...)
	ret0, _ := ret[0].(*grpc_generated_v2.SystemSharedMemoryRegisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SystemSharedMemoryRegister indicates an expected call of SystemSharedMemoryRegister.
func (mr *MockGRPCInferenceServiceClientMockRecorder) SystemSharedMemoryRegister(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SystemSharedMemoryRegister", reflect.TypeOf((*MockGRPCInferenceServiceClient)(nil).SystemSharedMemoryRegister), varargs...)
}

// SystemSharedMemoryStatus mocks base method.
func (m *MockGRPCInferenceServiceClient) SystemSharedMemoryStatus(ctx context.Context, in *grpc_generated_v2.SystemSharedMemoryStatusRequest, opts ...grpc.CallOption) (*grpc_generated_v2.SystemSharedMemoryStatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SystemSharedMemoryStatus", varargs...)
	ret0, _ := ret[0].(*grpc_generated_v2.SystemSharedMemoryStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SystemSharedMemoryStatus indicates an expected call of SystemSharedMemoryStatus.
func (mr *MockGRPCInferenceServiceClientMockRecorder) SystemSharedMemoryStatus(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SystemSharedMemoryStatus", reflect.TypeOf((*MockGRPCInferenceServiceClient)(nil).SystemSharedMemoryStatus), varargs...)
}

// SystemSharedMemoryUnregister mocks base method.
func (m *MockGRPCInferenceServiceClient) SystemSharedMemoryUnregister(ctx context.Context, in *grpc_generated_v2.SystemSharedMemoryUnregisterRequest, opts ...grpc.CallOption) (*grpc_generated_v2.SystemSharedMemoryUnregisterResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SystemSharedMemoryUnregister", varargs...)
	ret0, _ := ret[0].(*grpc_generated_v2.SystemSharedMemoryUnregisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SystemSharedMemoryUnregister indicates an expected call of SystemSharedMemoryUnregister.
func (mr *MockGRPCInferenceServiceClientMockRecorder) SystemSharedMemoryUnregister(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SystemSharedMemoryUnregister", reflect.TypeOf((*MockGRPCInferenceServiceClient)(nil).SystemSharedMemoryUnregister), varargs...)
}

// TraceSetting mocks base method.
func (m *MockGRPCInferenceServiceClient) TraceSetting(ctx context.Context, in *grpc_generated_v2.TraceSettingRequest, opts ...grpc.CallOption) (*grpc_generated_v2.TraceSettingResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TraceSetting", varargs...)
	ret0, _ := ret[0].(*grpc_generated_v2.TraceSettingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TraceSetting indicates an expected call of TraceSetting.
func (mr *MockGRPCInferenceServiceClientMockRecorder) TraceSetting(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TraceSetting", reflect.TypeOf((*MockGRPCInferenceServiceClient)(nil).TraceSetting), varargs...)
}

// MockGRPCInferenceServiceServer is a mock of GRPCInferenceServiceServer interface.
type MockGRPCInferenceServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockGRPCInferenceServiceServerMockRecorder
	isgomock struct{}
}

// MockGRPCInferenceServiceServerMockRecorder is the mock recorder for MockGRPCInferenceServiceServer.
type MockGRPCInferenceServiceServerMockRecorder struct {
	mock *MockGRPCInferenceServiceServer
}

// NewMockGRPCInferenceServiceServer creates a new mock instance.
func NewMockGRPCInferenceServiceServer(ctrl *gomock.Controller) *MockGRPCInferenceServiceServer {
	mock := &MockGRPCInferenceServiceServer{ctrl: ctrl}
	mock.recorder = &MockGRPCInferenceServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGRPCInferenceServiceServer) EXPECT() *MockGRPCInferenceServiceServerMockRecorder {
	return m.recorder
}

// CudaSharedMemoryRegister mocks base method.
func (m *MockGRPCInferenceServiceServer) CudaSharedMemoryRegister(arg0 context.Context, arg1 *grpc_generated_v2.CudaSharedMemoryRegisterRequest) (*grpc_generated_v2.CudaSharedMemoryRegisterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CudaSharedMemoryRegister", arg0, arg1)
	ret0, _ := ret[0].(*grpc_generated_v2.CudaSharedMemoryRegisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CudaSharedMemoryRegister indicates an expected call of CudaSharedMemoryRegister.
func (mr *MockGRPCInferenceServiceServerMockRecorder) CudaSharedMemoryRegister(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CudaSharedMemoryRegister", reflect.TypeOf((*MockGRPCInferenceServiceServer)(nil).CudaSharedMemoryRegister), arg0, arg1)
}

// CudaSharedMemoryStatus mocks base method.
func (m *MockGRPCInferenceServiceServer) CudaSharedMemoryStatus(arg0 context.Context, arg1 *grpc_generated_v2.CudaSharedMemoryStatusRequest) (*grpc_generated_v2.CudaSharedMemoryStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CudaSharedMemoryStatus", arg0, arg1)
	ret0, _ := ret[0].(*grpc_generated_v2.CudaSharedMemoryStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CudaSharedMemoryStatus indicates an expected call of CudaSharedMemoryStatus.
func (mr *MockGRPCInferenceServiceServerMockRecorder) CudaSharedMemoryStatus(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CudaSharedMemoryStatus", reflect.TypeOf((*MockGRPCInferenceServiceServer)(nil).CudaSharedMemoryStatus), arg0, arg1)
}

// CudaSharedMemoryUnregister mocks base method.
func (m *MockGRPCInferenceServiceServer) CudaSharedMemoryUnregister(arg0 context.Context, arg1 *grpc_generated_v2.CudaSharedMemoryUnregisterRequest) (*grpc_generated_v2.CudaSharedMemoryUnregisterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CudaSharedMemoryUnregister", arg0, arg1)
	ret0, _ := ret[0].(*grpc_generated_v2.CudaSharedMemoryUnregisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CudaSharedMemoryUnregister indicates an expected call of CudaSharedMemoryUnregister.
func (mr *MockGRPCInferenceServiceServerMockRecorder) CudaSharedMemoryUnregister(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CudaSharedMemoryUnregister", reflect.TypeOf((*MockGRPCInferenceServiceServer)(nil).CudaSharedMemoryUnregister), arg0, arg1)
}

// LogSettings mocks base method.
func (m *MockGRPCInferenceServiceServer) LogSettings(arg0 context.Context, arg1 *grpc_generated_v2.LogSettingsRequest) (*grpc_generated_v2.LogSettingsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogSettings", arg0, arg1)
	ret0, _ := ret[0].(*grpc_generated_v2.LogSettingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LogSettings indicates an expected call of LogSettings.
func (mr *MockGRPCInferenceServiceServerMockRecorder) LogSettings(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogSettings", reflect.TypeOf((*MockGRPCInferenceServiceServer)(nil).LogSettings), arg0, arg1)
}

// ModelConfig mocks base method.
func (m *MockGRPCInferenceServiceServer) ModelConfig(arg0 context.Context, arg1 *grpc_generated_v2.ModelConfigRequest) (*grpc_generated_v2.ModelConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelConfig", arg0, arg1)
	ret0, _ := ret[0].(*grpc_generated_v2.ModelConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModelConfig indicates an expected call of ModelConfig.
func (mr *MockGRPCInferenceServiceServerMockRecorder) ModelConfig(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelConfig", reflect.TypeOf((*MockGRPCInferenceServiceServer)(nil).ModelConfig), arg0, arg1)
}

// ModelInfer mocks base method.
func (m *MockGRPCInferenceServiceServer) ModelInfer(arg0 context.Context, arg1 *grpc_generated_v2.ModelInferRequest) (*grpc_generated_v2.ModelInferResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelInfer", arg0, arg1)
	ret0, _ := ret[0].(*grpc_generated_v2.ModelInferResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModelInfer indicates an expected call of ModelInfer.
func (mr *MockGRPCInferenceServiceServerMockRecorder) ModelInfer(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelInfer", reflect.TypeOf((*MockGRPCInferenceServiceServer)(nil).ModelInfer), arg0, arg1)
}

// ModelMetadata mocks base method.
func (m *MockGRPCInferenceServiceServer) ModelMetadata(arg0 context.Context, arg1 *grpc_generated_v2.ModelMetadataRequest) (*grpc_generated_v2.ModelMetadataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelMetadata", arg0, arg1)
	ret0, _ := ret[0].(*grpc_generated_v2.ModelMetadataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModelMetadata indicates an expected call of ModelMetadata.
func (mr *MockGRPCInferenceServiceServerMockRecorder) ModelMetadata(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelMetadata", reflect.TypeOf((*MockGRPCInferenceServiceServer)(nil).ModelMetadata), arg0, arg1)
}

// ModelReady mocks base method.
func (m *MockGRPCInferenceServiceServer) ModelReady(arg0 context.Context, arg1 *grpc_generated_v2.ModelReadyRequest) (*grpc_generated_v2.ModelReadyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelReady", arg0, arg1)
	ret0, _ := ret[0].(*grpc_generated_v2.ModelReadyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModelReady indicates an expected call of ModelReady.
func (mr *MockGRPCInferenceServiceServerMockRecorder) ModelReady(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelReady", reflect.TypeOf((*MockGRPCInferenceServiceServer)(nil).ModelReady), arg0, arg1)
}

// ModelStatistics mocks base method.
func (m *MockGRPCInferenceServiceServer) ModelStatistics(arg0 context.Context, arg1 *grpc_generated_v2.ModelStatisticsRequest) (*grpc_generated_v2.ModelStatisticsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelStatistics", arg0, arg1)
	ret0, _ := ret[0].(*grpc_generated_v2.ModelStatisticsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModelStatistics indicates an expected call of ModelStatistics.
func (mr *MockGRPCInferenceServiceServerMockRecorder) ModelStatistics(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelStatistics", reflect.TypeOf((*MockGRPCInferenceServiceServer)(nil).ModelStatistics), arg0, arg1)
}

// ModelStreamInfer mocks base method.
func (m *MockGRPCInferenceServiceServer) ModelStreamInfer(arg0 grpc.BidiStreamingServer[grpc_generated_v2.ModelInferRequest, grpc_generated_v2.ModelStreamInferResponse]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelStreamInfer", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ModelStreamInfer indicates an expected call of ModelStreamInfer.
func (mr *MockGRPCInferenceServiceServerMockRecorder) ModelStreamInfer(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelStreamInfer", reflect.TypeOf((*MockGRPCInferenceServiceServer)(nil).ModelStreamInfer), arg0)
}

// RepositoryIndex mocks base method.
func (m *MockGRPCInferenceServiceServer) RepositoryIndex(arg0 context.Context, arg1 *grpc_generated_v2.RepositoryIndexRequest) (*grpc_generated_v2.RepositoryIndexResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepositoryIndex", arg0, arg1)
	ret0, _ := ret[0].(*grpc_generated_v2.RepositoryIndexResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RepositoryIndex indicates an expected call of RepositoryIndex.
func (mr *MockGRPCInferenceServiceServerMockRecorder) RepositoryIndex(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepositoryIndex", reflect.TypeOf((*MockGRPCInferenceServiceServer)(nil).RepositoryIndex), arg0, arg1)
}

// RepositoryModelLoad mocks base method.
func (m *MockGRPCInferenceServiceServer) RepositoryModelLoad(arg0 context.Context, arg1 *grpc_generated_v2.RepositoryModelLoadRequest) (*grpc_generated_v2.RepositoryModelLoadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepositoryModelLoad", arg0, arg1)
	ret0, _ := ret[0].(*grpc_generated_v2.RepositoryModelLoadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RepositoryModelLoad indicates an expected call of RepositoryModelLoad.
func (mr *MockGRPCInferenceServiceServerMockRecorder) RepositoryModelLoad(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepositoryModelLoad", reflect.TypeOf((*MockGRPCInferenceServiceServer)(nil).RepositoryModelLoad), arg0, arg1)
}

// RepositoryModelUnload mocks base method.
func (m *MockGRPCInferenceServiceServer) RepositoryModelUnload(arg0 context.Context, arg1 *grpc_generated_v2.RepositoryModelUnloadRequest) (*grpc_generated_v2.RepositoryModelUnloadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepositoryModelUnload", arg0, arg1)
	ret0, _ := ret[0].(*grpc_generated_v2.RepositoryModelUnloadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RepositoryModelUnload indicates an expected call of RepositoryModelUnload.
func (mr *MockGRPCInferenceServiceServerMockRecorder) RepositoryModelUnload(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepositoryModelUnload", reflect.TypeOf((*MockGRPCInferenceServiceServer)(nil).RepositoryModelUnload), arg0, arg1)
}

// ServerLive mocks base method.
func (m *MockGRPCInferenceServiceServer) ServerLive(arg0 context.Context, arg1 *grpc_generated_v2.ServerLiveRequest) (*grpc_generated_v2.ServerLiveResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServerLive", arg0, arg1)
	ret0, _ := ret[0].(*grpc_generated_v2.ServerLiveResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ServerLive indicates an expected call of ServerLive.
func (mr *MockGRPCInferenceServiceServerMockRecorder) ServerLive(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServerLive", reflect.TypeOf((*MockGRPCInferenceServiceServer)(nil).ServerLive), arg0, arg1)
}

// ServerMetadata mocks base method.
func (m *MockGRPCInferenceServiceServer) ServerMetadata(arg0 context.Context, arg1 *grpc_generated_v2.ServerMetadataRequest) (*grpc_generated_v2.ServerMetadataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServerMetadata", arg0, arg1)
	ret0, _ := ret[0].(*grpc_generated_v2.ServerMetadataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ServerMetadata indicates an expected call of ServerMetadata.
func (mr *MockGRPCInferenceServiceServerMockRecorder) ServerMetadata(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServerMetadata", reflect.TypeOf((*MockGRPCInferenceServiceServer)(nil).ServerMetadata), arg0, arg1)
}

// ServerReady mocks base method.
func (m *MockGRPCInferenceServiceServer) ServerReady(arg0 context.Context, arg1 *grpc_generated_v2.ServerReadyRequest) (*grpc_generated_v2.ServerReadyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServerReady", arg0, arg1)
	ret0, _ := ret[0].(*grpc_generated_v2.ServerReadyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ServerReady indicates an expected call of ServerReady.
func (mr *MockGRPCInferenceServiceServerMockRecorder) ServerReady(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServerReady", reflect.TypeOf((*MockGRPCInferenceServiceServer)(nil).ServerReady), arg0, arg1)
}

// SystemSharedMemoryRegister mocks base method.
func (m *MockGRPCInferenceServiceServer) SystemSharedMemoryRegister(arg0 context.Context, arg1 *grpc_generated_v2.SystemSharedMemoryRegisterRequest) (*grpc_generated_v2.SystemSharedMemoryRegisterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SystemSharedMemoryRegister", arg0, arg1)
	ret0, _ := ret[0].(*grpc_generated_v2.SystemSharedMemoryRegisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SystemSharedMemoryRegister indicates an expected call of SystemSharedMemoryRegister.
func (mr *MockGRPCInferenceServiceServerMockRecorder) SystemSharedMemoryRegister(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SystemSharedMemoryRegister", reflect.TypeOf((*MockGRPCInferenceServiceServer)(nil).SystemSharedMemoryRegister), arg0, arg1)
}

// SystemSharedMemoryStatus mocks base method.
func (m *MockGRPCInferenceServiceServer) SystemSharedMemoryStatus(arg0 context.Context, arg1 *grpc_generated_v2.SystemSharedMemoryStatusRequest) (*grpc_generated_v2.SystemSharedMemoryStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SystemSharedMemoryStatus", arg0, arg1)
	ret0, _ := ret[0].(*grpc_generated_v2.SystemSharedMemoryStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SystemSharedMemoryStatus indicates an expected call of SystemSharedMemoryStatus.
func (mr *MockGRPCInferenceServiceServerMockRecorder) SystemSharedMemoryStatus(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SystemSharedMemoryStatus", reflect.TypeOf((*MockGRPCInferenceServiceServer)(nil).SystemSharedMemoryStatus), arg0, arg1)
}

// SystemSharedMemoryUnregister mocks base method.
func (m *MockGRPCInferenceServiceServer) SystemSharedMemoryUnregister(arg0 context.Context, arg1 *grpc_generated_v2.SystemSharedMemoryUnregisterRequest) (*grpc_generated_v2.SystemSharedMemoryUnregisterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SystemSharedMemoryUnregister", arg0, arg1)
	ret0, _ := ret[0].(*grpc_generated_v2.SystemSharedMemoryUnregisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SystemSharedMemoryUnregister indicates an expected call of SystemSharedMemoryUnregister.
func (mr *MockGRPCInferenceServiceServerMockRecorder) SystemSharedMemoryUnregister(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SystemSharedMemoryUnregister", reflect.TypeOf((*MockGRPCInferenceServiceServer)(nil).SystemSharedMemoryUnregister), arg0, arg1)
}

// TraceSetting mocks base method.
func (m *MockGRPCInferenceServiceServer) TraceSetting(arg0 context.Context, arg1 *grpc_generated_v2.TraceSettingRequest) (*grpc_generated_v2.TraceSettingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TraceSetting", arg0, arg1)
	ret0, _ := ret[0].(*grpc_generated_v2.TraceSettingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TraceSetting indicates an expected call of TraceSetting.
func (mr *MockGRPCInferenceServiceServerMockRecorder) TraceSetting(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TraceSetting", reflect.TypeOf((*MockGRPCInferenceServiceServer)(nil).TraceSetting), arg0, arg1)
}

// mustEmbedUnimplementedGRPCInferenceServiceServer mocks base method.
func (m *MockGRPCInferenceServiceServer) mustEmbedUnimplementedGRPCInferenceServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedGRPCInferenceServiceServer")
}

// mustEmbedUnimplementedGRPCInferenceServiceServer indicates an expected call of mustEmbedUnimplementedGRPCInferenceServiceServer.
func (mr *MockGRPCInferenceServiceServerMockRecorder) mustEmbedUnimplementedGRPCInferenceServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedGRPCInferenceServiceServer", reflect.TypeOf((*MockGRPCInferenceServiceServer)(nil).mustEmbedUnimplementedGRPCInferenceServiceServer))
}

// MockUnsafeGRPCInferenceServiceServer is a mock of UnsafeGRPCInferenceServiceServer interface.
type MockUnsafeGRPCInferenceServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeGRPCInferenceServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafeGRPCInferenceServiceServerMockRecorder is the mock recorder for MockUnsafeGRPCInferenceServiceServer.
type MockUnsafeGRPCInferenceServiceServerMockRecorder struct {
	mock *MockUnsafeGRPCInferenceServiceServer
}

// NewMockUnsafeGRPCInferenceServiceServer creates a new mock instance.
func NewMockUnsafeGRPCInferenceServiceServer(ctrl *gomock.Controller) *MockUnsafeGRPCInferenceServiceServer {
	mock := &MockUnsafeGRPCInferenceServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeGRPCInferenceServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeGRPCInferenceServiceServer) EXPECT() *MockUnsafeGRPCInferenceServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedGRPCInferenceServiceServer mocks base method.
func (m *MockUnsafeGRPCInferenceServiceServer) mustEmbedUnimplementedGRPCInferenceServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedGRPCInferenceServiceServer")
}

// mustEmbedUnimplementedGRPCInferenceServiceServer indicates an expected call of mustEmbedUnimplementedGRPCInferenceServiceServer.
func (mr *MockUnsafeGRPCInferenceServiceServerMockRecorder) mustEmbedUnimplementedGRPCInferenceServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedGRPCInferenceServiceServer", reflect.TypeOf((*MockUnsafeGRPCInferenceServiceServer)(nil).mustEmbedUnimplementedGRPCInferenceServiceServer))
}
